import { Inter, Roboto_Mono, Poppins } from 'next/font/google';
import './tokens.css';
import './globals.css';
import './utilities.css';

import Header from './components/Header/Header';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '700']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
